apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: employee
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests
    repoURL: 'https://github.com/subhakar-ci-cd-tools/spring-boot-emp-service-deployment'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
